name: Restrict Changes Outside /docs

on:
  pull_request:
    branches:
      - main

jobs:
  check-docs-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure only /docs is modified
        run: |
          git fetch origin main || exit 0

          if git rev-parse origin/main >/dev/null 2>&1; then
            CHANGED=$(git diff --name-only origin/main...HEAD | grep -v '^docs/')
            if [ -n "$CHANGED" ]; then
              echo "⛔️ Solo se permiten cambios dentro de la carpeta /docs. Los siguientes archivos están fuera:"
              echo "$CHANGED"
              exit 1
            else
              echo "✅ Solo se modificó la carpeta /docs"
            fi
          else
            echo "🟡 No se encontró origin/main aún. Saltando validación por ser primer push."
          fi
